name: ESLint + Prettier

on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run Prettier
        run: yarn run format

      - name: Run ESLint
        run: yarn run lint
